eval File.read(File.join(__dir__, "Brewfile.common"))

# Apps
cask "claude-code"
cask "dbeaver-community"
cask "docker-desktop"
cask "gcloud-cli"
cask "ghostty"
cask "google-chrome"
cask "obsidian"
cask "slack"
cask "visual-studio-code"
cask "zen-browser"
cask "zoom"

# Fonts
cask "font-fira-code"
cask "font-jetbrains-mono"
cask "font-cascadia-mono"
cask "font-3270-nerd-font"
cask "font-jetbrains-mono-nerd-font"
